add owner and specie table
chumaachike/vet-clinic pull request #4
Opened 2022-08-12 17:57 UTC by chumaachike

Added the Owner and Specie table ✔✔✔
Removed the specie column in animal table ✔✔✔✔
Ran queries as stipulated, please check out images to see results

2022-08-12 18:18 UTC, Danieldotcomcoder requested changes
Hello @chumaachike , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Professional Readme File ✔✔
- Clear and nice code ✔✔

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-08-12 18:18 UTC, Danieldotcomcoder commented on data.sql
> +/* If the name ends in "mon" it will be Digimon */
Kindly insert 'Pokemon' and 'Digimon 'into the species table , as requested in the project requirements 👍 😄

2022-08-12 18:18 UTC, Danieldotcomcoder commented on queries.sql
> + SELECT owners.full_name FROM owners JOIN animals ON owners.id = animals.owner_id WHERE animals.escape_attempts = ( SELECT MAX(animals.escape_attempts) FROM animals);
Kindly fix this query as it doesn't answer 'Who owns the most animals?' 👍 
You can add Count for this query . 😄

2022-08-13 05:41 UTC, CollinsTatang approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-13 16:30 UTC, merged